package com.codesense.driverapp.net;

public class WebserviceUrls {
    public static final String BASE_URL = "http://vavaonline.in/api/drive/";
    public static final String API_INFO = "api_info";
    public static final String COUNTRIES_LIST = "countries";
    public static final String CITIES_LIST = "cities";
    public static final String REGISTER_NEW_OWNER = "signup_owner";
    public static final String SIGNIN_OWNER = "signin_owner";
    public static final String SEND_OTP = "send_otp";
    public static final String VERIFY_OTP = "verify_otp";
    public static final String OWNER_TYPES = "owner_types";
    public static final String GET_OWNER_AGREEMENT = "get_owner_agreement";
    public static final String ACCEPT_LEGAL_AGREEMENT = "owner_registation/legal_agreement";
    public static final String REGISTATION_OWNER_TYPE = "owner_registation/owner_type";
    public static final String VEHICLE_TYPES = "vehicle_types";
    public static final String OWNER_CUM_DRIVER_STATUS = "get_documents_list/owner_cum_driver";
    public static final String NON_DRIVING_PARTNER_STATUS = "get_documents_list/non_driving_partner";
    public static final String UPLOAD_DOCUMENTS = "owner_registation/upload_documents";
    public static final String GET_AVAILABLE_VEHICLES = "get_available_vehicles";
    public static final String ADD_VEHICLE_TO_OWNER = "add_vehicle_to_owner";
    public static final String EDIT_DRIVER_VEHICLE = "edit_driver_vehicle";
    public static final String ADD_DRIVER_TO_OWNER = "add_driver_to_owner";
    public static final String EDIT_VEHICLE_DRIVER = "edit_vehicle_driver";
    public static final String GET_OWNER_VEHICLES = "get_owner_vehicles";
    public static final String OWNER_VEHICLES = "owner_vehicles";
    public static final String UPLOAD_OWNER_VEHICLE = "owner_vehicle";
    public static final String GET_ALL_DRIVERS_LIST = "get_all_drivers_list";
    public static final String DRIVER = "get_documents_list/driver";
    public static final String VEHICLE = "get_documents_list/vehicle";
    public static final String ADD_DRIVER_DOCUMENTS = "add_driver_documents";
    public static final String ADD_VEHICLE_DOCUMENTS = "add_vehicle_documents";
    public static final String DELETE_OWNER_VEHICLE = "delete_owner_vehicle";
    public static final String DELETE_DRIVER = "delete_driver";
    public static final String GET_OWNER_SIGNUP_STATUS = "get_owner_signup_status";
    public static final String CHANGE_MOBILE_NUMBER = "change_mobile_number";
    public static final String GET_AVAILABLE_DRIVERS = "get_available_drivers";
    public static final String SET_VEHICLE_LIVE_STATUS = "set_vehicle_live_status";
    public static final String UPDATE_VEHICLE_LIVE_LOCATION = "update_vehicle_live_location";
    public static final String HOME_SCREEN = "home_screen";
    public static final String GET_DOCUMENTS_STATUS = "owner_registation/get_documents_status";
    public static final String GET_DOCUMENTS_STATUS_VEHICLE = "get_documents_status/vehicle";
    public static final String GET_DOCUMENTS_STATUS_DRIVER = "get_documents_status/driver";
    public static final String UPDATE_DRIVER_DOCUMENTS = "update_driver_documents";
    public static final String ADD_VEHICLE_DRIVER = "add_vehicle_driver";
    public static final String GET_DRIVERS_LIST = "get_drivers_list";
    public static final String DRIVING_ACTIVATION = "driving_activation";
    public static final String DRIVER_DETAILS = "driver_details";
    //public static final String UPDATE_DRIVER_DOCUMENTS = "driver_details";

}
